# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 7/*

pool: Default

jobs: 
- job: valid
  variables:
    sample-path: $(Build.SourcesDirectory)/7/valid
  steps:
  - script: msbuild.bat
    workingDirectory: $(sample-path)
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(sample-path)
      publishLocation: 'pipeline'
- job: error
  variables:
    sample-path: $(Build.SourcesDirectory)/7/error
  steps:
  - script: msbuild.bat
    workingDirectory: $(sample-path)
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(sample-path)
      publishLocation: 'pipeline'
