# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 3/*

pool: Default

jobs:
- job: valid
  variables:
    sample-path: $(Build.SourcesDirectory)/3/valid
  steps:
  - powershell: ./build.ps1
    workingDirectory: $(sample-path)
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(sample-path)
      publishLocation: 'pipeline'
- job: error
  variables:
    sample-path: $(Build.SourcesDirectory)/3/error
  steps:
  - powershell: ./build.ps1
    workingDirectory: $(sample-path)
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(sample-path)
      publishLocation: 'pipeline'
